### ISSUE TITLE
Android 14?

### ISSUE THREAD

**Issue by User8395** [phhusson/treble_manifest#19]
Can I use the `master` branch to build an OS based on Android 14?

**Comment by phhusson** [comment]
No. You want https://github.com/TrebleDroid/treble_manifest/tree/android-14.0

**Comment by User8395** [comment]
Thank you

**Comment by User8395** [comment]
Perhaps you should update the guide and use LineageOS 21 as an example

**Comment by phhusson** [comment]
https://github.com/AndyCGYan/lineage_build_unified
